### ISSUE TITLE
[bug] Duplicates

### ISSUE THREAD

**Issue by Doaxan** [csn18/cities_app#2]
https://github.com/csn18/cities_app/blob/b6afd89c003ed82dbda346d1f6b8769e953c0db9/server.py#L44
https://github.com/csn18/cities_app/blob/b6afd89c003ed82dbda346d1f6b8769e953c0db9/server.py#L84

Please, follow the DRY principle. You can use functions for avoid duplicates.

**Comment by csn18** [comment]
Fixed.

**Comment by Doaxan** [comment]
Fixed.
