### ISSUE TITLE
[bug] /task5 does not work

### ISSUE THREAD

**Issue by Doaxan** [csn18/cities_app#5]
> jinja2.exceptions.TemplateNotFound
> jinja2.exceptions.TemplateNotFound: main/task5.html
>

**Comment by Doaxan** [comment]
@csn18 please create pull request for add working /task5 into master.

**Comment by csn18** [comment]
Fixed.

**Comment by Doaxan** [comment]
https://github.com/csn18/cities_app/pull/17 merged.
